print("SYÖTÄ HENKILÖTIEDOT")
print("-------------------")
print("")
etunimi = input("Anna etunimet: ")
sukunimi = input("Anna sukunimi: ")
pnumero = input("Anna puhelinnumero: ")
sposti = input("Anna sähköpostiosoite: ")
osoite = input("Anna lähiosoite: ")
postinumero = input("Anna postinumero: ")
kaupunki = input("Anna kaupunki: ")
maa = input("Anna maa: ")
syntymavuosi = int(input("Anna syntymävuosi: "))
ika = 2023 - syntymavuosi


print("")
print("KIITOS!")
print("")
print("")
print("HENKILÖN TIEDOT")
print("---------------")
print("")
print("NIMI:")
print(f"  {sukunimi}, {etunimi}")
print("PUH:")
print(f"  {pnumero}")
print("E-MAIL:")
print(f"  {sposti}")
print("OSOITE:")
print(f"  {osoite}")
print(f"  {pnumero} {kaupunki}")
print(f"  {maa}")
print(f"IKÄ: {ika}")